export const forest = {
    maxPoints: 45,
    maxSpecialPoints: 1,
    pointsRequiredForSpecial: 30,
    trees: [
        {
            id: 't1', name: 'Ho-oh', background: { src: 'ho-oh.png' }, foreground: { src: 'ho-oh_bg.png' },
            skills: [
                { id:"1", name:"Boost do Voo", x:1577 , y:570, type: "flyboost", value: "5", unit: "MS", desc:"Velocidade de Voo", connects_to: ["2","3","4","5"], prereqs: [], "isStart": true},
                { id:"2", name:"Instinto de Cura", x:1570, y:429 , type: "heal_instinct", value: "20", unit: "HP", desc:"Regenera o HP do seu Pokémon (fora de batalha e requer nível 101+)", connects_to:["1"], prereqs:["1"] },
                { id:"3", name:"Neverboost", x:1530, y:447 , type: "neverboost", value: "8", unit: "%", desc:"Chance do Pokémon remover efeitos negativos", connects_to:["1"], prereqs:["1"] },
                { id:"4", name:"Fruto Eterno", x:1497, y:474 , type: "berry_duration", value: "6", unit: "%", desc:"De duração de Berries", connects_to:["1"], prereqs:["1"] },
                { id:"5", name:"Boost de Equipamentos", x:1471, y:505 , type: "equipment_boost", value: "10", unit: "MS", desc:"Velocidade de Itens de Montaria e Profissão", connects_to:["1"], prereqs:["1"] },
                { id:"6", name:"Colhedor Sortudo", x:1368, y:938 , type: "lucky_collector", value: "1", unit: "%", desc:"Chance de Coleta Crítica de Profissão", connects_to:["1", "36", "7", "23", "25"], prereqs:["1"] },
                { id:"7", name:"Fury Strikes", x:1575, y:863 , type: "fury_strike_off", value: "1", unit: "%", desc:"Bônus de ataque de Pokémon (Off-Clã)", connects_to:["6", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17"], prereqs:["6"] },
                { id:"8", name:"Sharp Instinct", x:1456, y:1029 , type: "sharp_instinct_off", value: "2", unit: "%", desc:"Chance de acerto crítico de Pokémon (Off-Clã)", connects_to:["7"], prereqs:["7"] },
                { id:"9", name:"Neverboost", x:1512, y:1020 , type: "neverboost", value: "10", unit: "%", desc:"Chance do Pokémon remover efeitos negativos", connects_to:["7"], prereqs:["7"] },
                { id:"10", name:"Bastiao de Ferro", x:1560, y:1000 , type: "iron_bastion", value: "3", unit: "%", desc:"Bônus de Defesa em Batalha contra Pokémons de NPCs", connects_to:["7"], prereqs:["7"] },
                { id:"11", name:"Instinto Agressivo", x:1609, y:986 , type: "aggressive_instinct", value: "3", unit: "%", desc:"Bônus de Ataque em Batalhas contra Pokémon de NPCs", connects_to:["7"], prereqs:["7"] },
                { id:"12", name:"Recuperaçao Serena", x:1657, y:965 , type: "serene_recovery", value: "5", unit: "%", desc:"Regeneraçao de Energia Azul por intervalo em Mystery Dungeons", connects_to:["7"], prereqs:["7"] },
                { id:"13", name:"Nucleo Azul-Celeste", x:1701, y:949 , type: "blue_core", value: "5", unit: "", desc:"Capacidade de Energia Azul em Mystery Dungeons", connects_to:["7"], prereqs:["7"] },
                { id:"14", name:"Capturador Confiavel", x:1747, y:920 , type: "trusty_catcher", value: "1", unit: "%", desc:"Taxa de Captura aumentada para Pokémon que não são Shinies", connects_to:["7"], prereqs:["7"] },
                { id:"15", name:"Colhedor Sortudo", x:1787, y:890 , type: "lucky_collector", value: "1", unit: "%", desc:"Chance de Coleta Crítica de Profissão", connects_to:["7"], prereqs:["7"] },
                { id:"16", name:"Recuperaçao Serena", x:1824, y:862 , type: "serene_recovery", value: "5", unit: "%", desc:"Regeneração de Energia Azul por intervalo em Mystery Dungeons", connects_to:["7"], prereqs:["7"] },
                { id:"17", name:"Surto de Exp", x:1826, y:730 , type: "exp_surge", value: "2", unit: "%", desc:"Bônus de EXP", connects_to:["7", "18", "19", "20", "21", "22"], prereqs:["7"] },
                { id:"18", name:"Saqueador Dimensional", x:1869, y:821, type: "dimensional_looter", value: "2", unit: "%", desc:"Bônus de Saque em Zonas Dimensionais", connects_to:["17"], prereqs:["17"] },
                { id:"19", name:"Saqueador Dimensional", x:1909, y:771 , type: "dimensional_looter", value: "3", unit: "%", desc:"Bônus de Saque em Zonas Dimensionais", connects_to:["17"], prereqs:["17"] },
                { id:"20", name:"Surto de EXP Dimensional", x:1945, y:718 , type: "dimensional_exp_surge", value: "3", unit: "%", desc:"Bônus de EXP em Zonas Dimensionais", connects_to:["17"], prereqs:["17"] },
                { id:"21", name:"Surto de EXP Dimensional", x:1972, y:652 , type: "dimensional_exp_surge", value: "3", unit: "%", desc:"Bônus de EXP em Zonas Dimensionais", connects_to:["17"], prereqs:["17"] },
                { id:"22", name:"Conhecimiento de Captura", x:1982, y:597 , type: "capture_knowledge", value: "2", unit: "%", desc:"Bônus de EXP em Daily Catch", connects_to:["17"], prereqs:["17"] },
                { id: "23", name: "Boost do Voo", x:1307, y:1224, type: "flyboost", value: "5", unit: "MS", desc:"Velocidade de Voo", connects_to: ["6", "24"], prereqs: ["6"] },
                { id: "24", name: "Instinto Aguçado", x:1390, y:1256, type: "sharp_instinct", value: "1", unit: "%", desc:"Chance de Golpe Crítico do Pokémon", connects_to: ["23"], prereqs: ["23"]},
                { id: "25", name: "Núcleo Azul-Celeste", x:1158, y:1161, type: "blue_core", value: "5", unit: "", desc:"Capacidade de Energia Azul em Mystery Dungeons", connects_to: ["6", "26", "29", "32"], prereqs: ["6"]},
                { id: "26", name: "Núcleo Azul-Celeste", x:1173, y:1253, type: "blue_core", value: "8", unit: "", desc:"Capacidade de Energia Azul em Mystery Dungeons", connects_to: ["25", "28", "27"], prereqs: ["25"]},
                { id: "27", name: "Fluxo Ardente", x:1165, y:1365, type: "burning_flow", value: "5", unit: "%", desc:"Regeneração de Energia Vermelha por intervalo em Mystery Dungeons", connects_to: ["26"], prereqs: ["26"]},
                { id: "28", name: "Instinto Aguçado", x:1030, y:1483, type: "sharp_instinct", value: "1", unit: "%", desc:"Chance de Golpe Crítico do Pokémon", connects_to: ["26", "30"], prereqs: ["26", "30"]},
                { id: "29", name: "Instinto de Cura", x:1101, y:1215, type: "heal_instinct", value: "60", unit: "HP", desc:"Regenera o HP do seu Pokémon (fora de batalha e requer nível 101+)", connects_to: ["25", "30"], prereqs: ["25"]},
                { id: "30", name: "Fruto Eterno", x:992, y:1325, type: "berry_duration", value: "6", unit: "%", desc:"Duração de Berries", connects_to: ["29", "28", "31", "34"], prereqs: ["29", "28", "34"]},
                { id: "31", name: "Capturador Eficiente", x:881, y:1406, type: "efficient_catcher", value: "6", unit: "%", desc:"Reduçao de Poké Bolas Usadas para capturar Pokémon no Sistema de Captura", connects_to: ["30"], prereqs: ["30"]},
                { id: "32", name: "Fruto Eterno", x:943, y:1119, type: "berry_duration", value: "6", unit: "%", desc:"Duração de Berries", connects_to: ["25", "33"], prereqs: ["25"]},
                { id: "33", name: "Fury Strike (off-cla)", x:806, y:1190, type: "fury_strike_off", value: "1", unit: "%", desc:"Bônus de ataque de Pokémon (Off-Clã)", connects_to: ["32", "34", "35"], prereqs: ["32", "34"]},
                { id: "34", name: "Colhedor Sortudo", x:806, y:1338, type: "lucky_collector", value: "1.5", unit: "%", desc:"Chance de Coleta Crítica de Profissão", connects_to: ["30", "33"], prereqs: ["30", "33"]},
                { id: "35", name: "Golpe de Fúria", x:762, y:1245, type: "fury_strike", value: "1", unit: "%", desc:"Bônus de Ataque do Pokémon", connects_to: ["33"], prereqs: ["33"]},
                { id: "36", name: "Surto de EXP", x:1090, y:604, type: "exp_surge", value: "2", unit: "%", desc:"Bônus de EXP", connects_to: ["6", "37", "38", "39", "40", "51", "41", "45"], prereqs: ["6"]},
                { id: "37", name: "Fortuna Dourada", x:1103, y:929, type: "golden_fortune", value: "1", unit: "%", desc:"Bônus de Saque", connects_to: ["36"], prereqs: ["36"]},
                { id: "38", name: "Recuperação Serena", x:1014, y:850, type: "serene_recovery", value: "5", unit: "%", desc:"Regeneração de Energia Azul por intervalo em Mystery Dungeons", connects_to: ["36"], prereqs: ["36"]},
                { id: "39", name: "Surto de EXP", x:950, y:812, type: "exp_surge", value: "2", unit: "%", desc:"Bônus de EXP", connects_to: ["36"], prereqs: ["36"]},
                { id: "40", name: "Espírito Resiliente", x:908, y:760, type: "resilient_spirit", value: "2", unit: "%", desc:"HP Máximo do jogador", connects_to: ["36"], prereqs: ["36"]},
                { id: "41", name: "Capturador Confiável", x:989, y:530, type: "trusty_catcher", value: "1", unit: "%", desc:"Taxa de Captura aumentada para Pokémon que não são Shinies", connects_to: ["36", "42", "43", "44"], prereqs: ["36"]},
                { id: "42", name: "Especialista em Premier Balls", x:805, y:614, type: "pb_specialist", value: "2", unit: "%", desc:"Taxa de Captura aumentada com Premier Ball", connects_to: ["41"], prereqs: ["41"]},
                { id: "43", name: "Capturador Engenheiro", x:772, y:533, type: "engineer_catcher", value: "2", unit: "%", desc:"Taxa de Captura aumentada com Poké Balls criadas por Engenheiro (Rank A)", connects_to: ["41"], prereqs: ["41"]},
                { id: "44", name: "Especialista em Ultra Balls", x:753, y:450, type: "ub_specialist", value: "4", unit: "%", desc:"Taxa de Captura aumentada com Ultra Balls", connects_to: ["41"], prereqs: ["41"]},
                { id: "45", name: "Especialista em Poké Balls", x:932, y:369, type: "poke_ball_specialist", value: "6", unit: "%", desc:"Taxa de Captura aumentada com Poké Bolas abaixo Ultra Balls", connects_to: ["36", "46", "47", "48", "49", "50"], prereqs: ["36"]},
                { id: "46", name: "Mestre de Capturas", x:730, y:352, type: "catch_master", value: "1", unit: "%", desc:"Taxa de Captura aumentada", connects_to: ["45"], prereqs: ["45"]},
                { id: "47", name: "Capturador Elemental", x:725, y:254, type: "elemental_catcher_1", value: "3", unit: "%", desc:"Taxa de Captura aumentada para Pokémon dos tipos Lutador, Noturno, Fada e Normal", connects_to: ["45"], prereqs: ["45"]},
                { id: "48", name: "Capturador Elemental", x:753, y:165, type: "elemental_catcher_2", value: "3", unit: "%", desc:"Taxa de Captura aumentada para Pokémon dos tipos Elétrico, Voador, Dragão, Psíquico e Fantasma", connects_to: ["45"], prereqs: ["45"]},
                { id: "49", name: "Capturador Elemental", x:808, y:81, type: "elemental_catcher_3", value: "3", unit: "%", desc:"Taxa de Captura aumentada para Pokémon dos tipos Água, Planta, Fogo e Inseto", connects_to: ["45"], prereqs: ["45"]},
                { id: "50", name: "Capturador Elemental", x:927, y:121, type: "elemental_catcher_4", value: "3", unit: "%", desc:"Taxa de Captura aumentada para Pokémon dos tipos Terra, Pedra, Cristal, Veneno, Metal e Gelo", connects_to: ["45"], prereqs: ["45"]},
                { id: "51", name: "Espírito Resiliente", x:850, y:690, type: "resilient_spirit", value: "2", unit: "%", desc:"HP Máximo do jogador", connects_to: ["36"], prereqs: ["36"]},
                { id: "52", name: "Desafiante de NPC", x:1269, y:242, type: "npc_challenger", value: "5", unit: "%", desc:"Fortalecidos pela Chama Sagrada do Ho-Oh, seus Pokémon recebem um bônus de Ataque e Defesa em batalhas contra NPCs", connects_to: [], prereqs: [], isSpecial: true},
                { id: "53", name: "Drenador de Vida", x:1389, y:242, type: "life_drain", value: "3", unit: "%", desc:"Fortalecido pela Chama Sagrada do Ho-Oh, marca un inimigo por 5s após o ataque, e seu Pokémon ganha Roubo de Vida contra ele (apenas 1% contra Bosses no PokéView)", connects_to: [], prereqs: [], isSpecial: true}
            ]
        },
        {
            id: 't2', name: 'Celebi', background: { src: 'celebi.png' }, foreground: { src: 'celebi_bg.png' },
            skills: [
                { id:"1", name:"Boost de Equipamentos", x:751, y:854, type: "equipment_boost", value: "5", unit: "MS", desc:"Velocidade de Itens de Montaria e Profissão", connects_to: ["2", "3", "4", "6", "7"], prereqs: [], isStart: true },
                { id:"2", name:"Instinto de Cura", x:841, y:905 , type: "heal_instinct", value: "20", unit: "HP", desc:"Regenera o HP do seu Pokémon (fora de batalha e requer nível 101+)", connects_to: ["1"], prereqs:["1"] },
                { id:"3", name:"Fluxo Temporal", x:863, y:1062 , type: "temporal_flow", value: "3", unit: "%", desc:"Redução do Tempo de Recarga do Teletransporte", connects_to: ["1"], prereqs:["1"] },
                { id:"4", name:"Fluxo Temporal", x:682, y:873 , type: "temporal_flow", value: "3", unit: "%", desc:"Redução do Tempo de Recarga do Teletransporte", connects_to: ["1"], prereqs:["1"] },
                { id:"5", name:"Maestria em Poções", x:719, y:786 , type: "potion_mastery", value: "5", unit: "%", desc:"Poder de Cura de Poções", connects_to: ["1"], prereqs:["1"] },
                { id:"6", name:"Fluxo Temporal", x:789, y:804 , type: "temporal_flow", value: "3", unit: "%", desc:"Redução do Tempo de Recarga do Teletransporte", connects_to: ["1"], prereqs:["1"] },
                { id:"7", name:"Capturador Confiável", x:845, y:741 , type: "trusty_catcher", value: "1", unit: "%", desc:"Taxa de Captura aumentada para Pokémon que não são Shinies", connects_to: ["1", "8", "11"], prereqs:["1"] },
                { id:"8", name:"Fluxo Temporal", x:835, y:647 , type: "temporal_flow", value: "3", unit: "%", desc:"Redução do Tempo de Recarga do Teletransporte", connects_to: ["7", "9"], prereqs:["7"] },
                { id:"9", name:"Colhedor Sortudo", x:861, y:500 , type: "lucky_collector", value: "1", unit: "%", desc:"Chance de Coleta Crítica de Profissão", connects_to: ["8", "10"], prereqs:["8"] },
                { id:"10", name:"Pés Ligeiros", x:936, y:379 , type: "light_feet", value: "5", unit: "MS", desc:"Velocidade de Movimento do jogador", connects_to: ["9"], prereqs:["9"] },
                { id:"11", name:"Fluxo Temporal", x:1038, y:746 , type: "temporal_flow", value: "3", unit: "%", desc:"Redução do Tempo de Recarga do Teletransporte", connects_to: ["7", "12", "15", "19"], prereqs:["7"] },
                { id:"12", name:"Especialista em Poké Balls", x:1024, y:595 , type: "poke_ball_specialist", value: "6", unit: "%", desc:"Taxa de Captura aumentada com Poké Bolas abaixo Ultra Balls", connects_to: ["11", "13", "14"], prereqs:["11"] },
                { id:"13", name:"Neverboost", x:929, y:654 , type: "neverboost", value: "10", unit: "%", desc:"Chance do Pokémon remover efeitos negativos", connects_to: ["12"], prereqs:["12"] },
                { id:"14", name:"Capturador Confiável", x:1141, y:552 , type: "trusty_catcher", value: "1", unit: "%", desc:"Taxa de Captura aumentada para Pokémon que não são Shinies", connects_to: ["12"], prereqs:["12"] },
                { id:"15", name:"Surto de EXP", x:1128, y:710 , type: "exp_surge", value: "2", unit: "%", desc:"Bônus de EXP", connects_to: ["11", "16"], prereqs:["11"] },
                { id:"16", name:"Conhecimento de Caça", x:1192, y:621 , type: "hunting_knowledge", value: "2", unit: "%", desc:"Bônus de EXP em Daily Kill", connects_to: ["15", "17"], prereqs:["15"] },
                { id:"17", name:"Surto de EXP", x:1288, y:522 , type: "exp_surge", value: "3", unit: "%", desc:"Bônus de EXP", connects_to: ["16", "18"], prereqs:["16"] },
                { id:"18", name:"Conhecimento de Caça", x:1355, y:464 , type: "hunting_knowledge", value: "3", unit: "%", desc:"Bônus de EXP em Daily Kill", connects_to: ["17"], prereqs:["17"] },
                { id:"19", name:"Boost de Equipamentos", x:1383, y:741 , type: "equipment_boost", value: "5", unit: "MS", desc:"Velocidade de Itens de Montaria e Profissão", connects_to: ["11", "20", "23", "25", "27", "29"], prereqs:["11"] },
                { id:"20", name:"Surto de EXP Dimensional", x:1390, y:527 , type: "dimensional_exp_surge", value: "3", unit: "%", desc:"Bônus de EXP em Zonas Dimensionais", connects_to: ["19", "21"], prereqs:["19", "21"] },
                { id:"21", name:"Surto de EXP Dimensional", x:1423, y:457 , type: "dimensional_exp_surge", value: "3", unit: "%", desc:"Bônus de EXP em Zonas Dimensionais", connects_to: ["20", "22"], prereqs:["20", "22"] },
                { id:"22", name:"Capturador de Shinies", x:1473, y:227 , type: "shiny_catcher", value: "3", unit: "%", desc:"Taxa de Captura aumentada para Pokémon Shinies", connects_to: ["21", "24", "26", "28"], prereqs:["21", "24", "26", "28"] },
                { id:"23", name:"Boost de Voo", x:1444, y:571 , type: "flyboost", value: "5", unit: "MS", desc:"Velocidade de Voo", connects_to: ["19", "24"], prereqs:["19", "24"] },
                { id:"24", name:"Fluxo Temporal", x:1471, y:476 , type: "temporal_flow", value: "3", unit: "%", desc:"Redução do Tempo de Recarga do Teletransporte", connects_to: ["22", "23"], prereqs:["22", "23"] },
                { id:"25", name:"Surto de EXP Dimensional", x:1510, y:590 , type: "dimensional_exp_surge", value: "3", unit: "%", desc:"Bônus de EXP em Zonas Dimensionais", connects_to: ["19", "26"], prereqs:["19", "26"] },
                { id:"26", name:"Surto de EXP Dimensional", x:1525, y:496 , type: "dimensional_exp_surge", value: "3", unit: "%", desc:"Bônus de EXP em Zonas Dimensionais", connects_to: ["25", "22"], prereqs:["25", "22"] },
                { id:"27", name:"Núcleo Azul-Celeste", x:1572, y:586, type: "blue_core", value: "5", unit: "", desc:"Capacidade de Energia Azul em Mystery Dungeons", connects_to: ["19", "28"], prereqs:["19", "28"] },
                { id:"28", name:"Núcleo Azul-Celeste", x:1574, y:506, type: "blue_core", value: "5", unit: "", desc:"Capacidade de Energia Azul em Mystery Dungeons", connects_to: ["27", "22"], prereqs:["27", "22"] },
                { id:"29", name:"Fluxo Temporal", x:1506, y:925 , type: "temporal_flow", value: "3", unit: "%", desc:"Redução do Tempo de Recarga do Teletransporte", connects_to: ["19", "30", "33"], prereqs:["19"] },
                { id:"30", name:"Surto de EXP", x:1573, y:896 , type: "exp_surge", value: "2", unit: "%", desc:"Bônus de EXP", connects_to: ["29", "31"], prereqs:["29"] },
                { id:"31", name:"Surto de EXP", x:1656, y:855 , type: "exp_surge", value: "3", unit: "%", desc:"Bônus de EXP", connects_to: ["30", "32"], prereqs:["30"] },
                { id:"32", name:"Instinto Botânico", x:1748, y:797 , type: "botanical_instinct", value: "5", unit: "%", desc:"Chance de Coleta Crítica de Berries", connects_to: ["31"], prereqs:["31"] },
                { id:"33", name:"Conhecimento de Captura", x:1378, y:1084 , type: "capture_knowledge", value: "3", unit: "%", desc:"Bônus de EXP em Daily Catch", connects_to: ["29", "39", "37", "34"], prereqs:["29"] },
                { id:"34", name:"Conhecimento de Caça", x:1517, y:1053 , type: "hunting_knowledge", value: "3", unit: "%", desc:"Bônus de EXP em Daily Kill", connects_to: ["33", "35"], prereqs:["33", "35"] },
                { id:"35", name:"Conhecimento de Caça", x:1724, y:1058 , type: "hunting_knowledge", value: "3", unit: "%", desc:"Bônus de EXP em Daily Kill", connects_to: ["34", "36"], prereqs:["34", "36"] },
                { id:"36", name:"Conhecimento de Captura", x:1894, y:1094 , type: "capture_knowledge", value: "6", unit: "%", desc:"Bônus de EXP em Daily Catch", connects_to: ["35", "38"], prereqs:["35", "38"] },
                { id:"37", name:"Núcleo Carmesim", x:1518, y:1148 , type: "crimson_core", value: "5", unit: "", desc:"Capacidade de Energia Vermelha em Mystery Dungeons", connects_to: ["33", "38"], prereqs:["33", "38"] },
                { id:"38", name:"Fluxo Ardente", x:1739, y:1136 , type: "burning_flow", value: "5", unit: "%", desc:"Regeneração de Energia Vermelha por intervalo em Mystery Dungeons", connects_to: ["37", "36"], prereqs:["37", "36"] },
                { id:"39", name:"Boost de Voo", x:1329, y:1170 , type: "flyboost", value: "5", unit: "MS", desc:"Velocidade de Voo", connects_to: ["33", "40", "45", "46", "47", "48", "49"], prereqs:["33"] },
                { id:"40", name:"Especialista em Premier Balls", x:1465, y:1273 , type: "pb_specialist", value: "1", unit: "%", desc:"Taxa de Captura aumentada com Premier Ball", connects_to: ["39", "41", "42", "43", "44"], prereqs:["39"] },
                { id:"41", name:"Arremesso Perfeito", x:1430, y:1201 , type: "perfect_throw", value: "2", unit: "%", desc:"Chance de Captura Crítica", connects_to: ["40"], prereqs:["40"] },
                { id:"42", name:"Maestria em Defesa", x:1503, y:1223 , type: "defense_mastery", value: "2", unit: "%", desc:"Chance de Bloquear Ataques de Pokémon", connects_to: ["40"], prereqs:["40"] },
                { id:"43", name:"Instinto Aguçado", x:1487, y:1337 , type: "sharp_instinct", value: "1", unit: "%", desc:"Chance de Golpe Crítico do Pokémon", connects_to: ["40"], prereqs:["40"] },
                { id:"44", name:"Fluxo Temporal", x:1417, y:1317 , type: "temporal_flow", value: "5", unit: "%", desc:"Redução do Tempo de Recarga do Teletransporte", connects_to: ["40"], prereqs:["40"] },
                { id:"45", name:"Conhecimento de Caça", x:1247, y:1313 , type: "hunting_knowledge", value: "5", unit: "%", desc:"Bônus de EXP em Daily Kill", connects_to: ["39"], prereqs:["39"] },
                { id:"46", name:"Recuperação Serena", x:1271, y:906 , type: "serene_recovery", value: "5", unit: "%", desc:"Regeneração de Energia Azul por intervalo em Mystery Dungeons", connects_to: ["39"], prereqs:["39"] },
                { id:"47", name:"Instinto Botânico", x:1175, y:966 , type: "botanical_instinct", value: "3", unit: "%", desc:"Chance de Coleta Crítica de Berries", connects_to: ["39"], prereqs:["39"] },
                { id:"48", name:"Recuperação Serena", x:1117, y:1073 , type: "serene_recovery", value: "5", unit: "%", desc:"Regeneração de Energia Azul por intervalo em Mystery Dungeons", connects_to: ["39"], prereqs:["39"] },
                { id:"49", name:"Especialista em Premier Balls", x:1069, y:1154 , type: "pb_specialist", value: "1", unit: "%", desc:"Taxa de Captura aumentada com Premier Ball", connects_to: ["39", "50"], prereqs:["39"] },
                { id:"50", name:"Fluxo Ardente", x:1018, y:1162 , type: "burning_flow", value: "5", unit: "%", desc:"Regeneração de Energia Vermelha por intervalo em Mystery Dungeons", connects_to: ["49", "51"], prereqs:["49"] },
                { id:"51", name:"Fortuna Dourada", x:970, y:1137 , type: "golden_fortune", value: "2", unit: "%", desc:"Bônus de Saque", connects_to: ["50"], prereqs:["50"] },
                { id:"52", name:"Viajante do Eco", x:1638, y:317 , type: "echo_traveler", value: "TP", unit: "", desc:"Guiado pela Bênção do Celebi, o jogador pode se teleportar para áreas avançadas além das cidades", connects_to: [], prereqs:[], isSpecial: true },
                { id:"53", name:"Caçador de Ecos", x:1758, y:317 , type: "echo_hunter", value: "RB", unit: "", desc:"Guiado pela Bênção do Celebi, após usar uma Repeat Ball, você pode jogar uma Poké Bola extra (até 1x por dia). Este efeito não funciona em Dungeons ou Zonas Dimensionais", connects_to: [], prereqs:[], isSpecial: true }

            ]
        },
        {
            id: 't3', name: 'Lugia', background: { src: 'lugia.png' }, foreground: { src: 'lugia_bg.png' },
            skills: [
                { id:"1", name:"Corredor das Marés", x:853, y:900, type: "tide_runner", value: "15", unit: "MS", desc:"Velocidade de Surfe", connects_to: ["2"], prereqs: [], isStart: true },
                { id:"2", name:"Boost de Voo", x:804, y:984, type: "flyboost", value: "5", unit: "MS", desc:"Velocidade de Voo", connects_to: ["3"], prereqs: ["1"] },
                { id:"3", name:"Corredor das Marés", x:692, y:788, type: "tide_runner", value: "15", unit: "MS", desc:"Velocidade de Surfe", connects_to: ["2"], prereqs: ["2"] },
                { id:"4", name:"Boost de Voo", x:801, y:729, type: "flyboost", value: "5", unit: "MS", desc:"Velocidade de Voo", connects_to: ["3", "5", "6", "7"], prereqs: ["3"] },
                { id:"5", name:"Mergulhador das Profundezas", x:724, y:593, type: "deep_diver", value: "20", unit: "MS", desc:"Velocidade de Mergulho", connects_to: ["4"], prereqs: ["4"] },
                { id:"6", name:"Maestria em Iscas", x:801, y:555, type: "bait_mastery", value: "5", unit: "%", desc:"Velocidade de Pesca", connects_to: ["4"], prereqs: ["4"] },
                { id:"7", name:"Caminhante do Gelo", x:997, y:591, type: "ice_walker", value: "10", unit: "MS", desc:"Velocidade de Movimentaçao na Neve", connects_to: ["4", "8"], prereqs: ["4"] },
                { id:"8", name:"Boost de Voo", x:1327, y:529, type: "flyboost", value: "5", unit: "MS", desc:"Velocidade de Voo", connects_to: ["7", "9"], prereqs: ["7"] },
                { id:"9", name:"Capturador Confiável", x:1209, y:270, type: "trusty_catcher", value: "1", unit: "%", desc:"Taxa de Captura aumentada para Pokémon que não são Shinies", connects_to: ["8", "10", "11", "12"], prereqs: ["8"] },
                { id:"10", name:"Capturador Engenheiro", x:1106, y:226, type: "engineer_catcher", value: "2", unit: "%", desc:"Taxa de Captura aumentada com Poké Balls criadas por Engenheiro (Rank A)", connects_to: ["9"], prereqs: ["9"] },
                { id:"11", name:"Especialista em Ultra Balls", x:1167, y:170, type: "ub_specialist", value: "4", unit: "%", desc:"Taxa de Captura aumentada com Ultra Balls", connects_to: ["9"], prereqs: ["9"] },
                { id:"12", name:"Surto de EXP", x:1422, y:373, type: "exp_surge", value: "2", unit: "%", desc:"Bônus de EXP", connects_to: ["9", "13", "15", "17"], prereqs: ["9"] },
                { id:"13", name:"Capturador Elemental", x:1358, y:185, type: "elemental_catcher_4", value: "2", unit: "%", desc:"Taxa de Captura aumentada para Pokémon dos tipos Terra, Pedra, Cristal, Veneno, Metal e Gelo", connects_to: ["14", "12"], prereqs: ["12"] },
                { id:"14", name:"Capturador Elemental", x:1486, y:132, type: "elemental_catcher_4", value: "3", unit: "%", desc:"Taxa de Captura aumentada para Pokémon dos tipos Terra, Pedra, Cristal, Veneno, Metal e Gelo", connects_to: ["13"], prereqs: ["13"] },
                { id:"15", name:"Capturador Elemental", x:1632, y:368, type: "elemental_catcher_3", value: "2", unit: "%", desc:"Taxa de Captura aumentada para Pokémon dos tipos Água, Planta, Fogo e Inseto", connects_to: ["16", "12"], prereqs: ["12"] },
                { id:"16", name:"Capturador Elemental", x:1640, y:260, type: "elemental_catcher_3", value: "3", unit: "%", desc:"Taxa de Captura aumentada para Pokémon dos tipos Água, Planta, Fogo e Inseto", connects_to: ["15"], prereqs: ["15"] },
                { id:"17", name:"Fortuna Dourada", x:1659, y:659, type: "golden_fortune", value: "2", unit: "%", desc:"Bônus de Saque", connects_to: ["12", "18", "20", "22"], prereqs: ["12"] },
                { id:"18", name:"Capturador Elemental", x:1770, y:509, type: "elemental_catcher_2", value: "2", unit: "%", desc:"Taxa de Captura aumentada para Pokémon dos tipos Elétrico, Voador, Dragão, Psíquico e Fantasma", connects_to: ["19", "17"], prereqs: ["17"] },
                { id:"19", name:"Capturador Elemental", x:1763, y:410, type: "elemental_catcher_2", value: "3", unit: "%", desc:"Taxa de Captura aumentada para Pokémon dos tipos Elétrico, Voador, Dragão, Psíquico e Fantasma", connects_to: ["18"], prereqs: ["18"] },
                { id:"20", name:"Capturador Elemental", x:1856, y:686, type: "elemental_catcher_1", value: "2", unit: "%", desc:"Taxa de Captura aumentada para Pokémon dos tipos Lutador, Noturno, Fada e Normal", connects_to: ["21", "17"], prereqs: ["17"] },
                { id:"21", name:"Capturador Elemental", x:1853, y:599, type: "elemental_catcher_1", value: "3", unit: "%", desc:"Taxa de Captura aumentada para Pokémon dos tipos Lutador, Noturno, Fada e Normal", connects_to: ["21"], prereqs: ["20"] },
                { id:"22", name:"Blindado", x:1510, y:664, type: "armored", value: "2", unit: "%", desc:"Defesa do jogador", connects_to: ["17", "23"], prereqs: ["17"] },
                { id:"23", name:"Espírito Resiliente", x:1414, y:785, type: "resilient_spirit", value: "2", unit: "%", desc:"HP Máximo do jogador", connects_to: ["22", "27", "28", "29", "30", "24", "25", "26"], prereqs: ["22"] },
                { id:"24", name:"Mestre da Pesca", x:1728, y:795, type: "fishing_master", value: "10", unit: "%", desc:"Bônus de EXP para a Habilidade de Pesca", connects_to: ["23"], prereqs: ["23"] },
                { id:"25", name:"Corredor das Marés", x:1751, y:934, type: "tide_runner", value: "20", unit: "MS", desc:"Velocidade de Surfe", connects_to: ["23"], prereqs: ["23"] },
                { id:"26", name:"Caminhante do Gelo", x:1765, y:1080, type: "ice_walker", value: "20", unit: "MS", desc:"Velocidade de Movimentaçao na Neve", connects_to: ["23"], prereqs: ["23"] },
                { id:"27", name:"Boost de Voo", x:1043, y:716, type: "flyboost", value: "20", unit: "MS", desc:"Velocidade de Voo", connects_to: ["23"], prereqs: ["23"] },
                { id:"28", name:"Recuperação Serena", x:1065, y:839, type: "serene_recovery", value: "6", unit: "%", desc:"Regeneração de Energia Azul por intervalo em Mystery Dungeons", connects_to: ["23"], prereqs: ["23"] },
                { id:"29", name:"Surto de EXP", x:1173, y:877, type: "exp_surge", value: "3", unit: "%", desc:"Bônus de EXP", connects_to: ["23"], prereqs: ["23"] },
                { id:"30", name:"Pés Ligeiros", x:1439, y:1180, type: "light_feet", value: "5", unit: "MS", desc:"Velocidade de Movimento do jogador", connects_to: ["23"], prereqs: ["23"] },
                { id:"31", name:"Muralha de Metal", x:1648, y:1257, type: "metal_wall", value: "2", unit: "%", desc:"Bônus de Defesa do Pokémon", connects_to: ["30"], prereqs: ["30"] },
                { id:"32", name:"Aliado Confiável", x:1299, y:1074, type: "trusty_ally_level", value: "5", unit: "%", desc:"Bônus de Nível de Pokémon Ajudantes", connects_to: ["30"], prereqs: ["30"] },
                { id:"33", name:"Aliado Confiável", x:1240, y:1133, type: "trusty_ally_duration", value: "10", unit: "%", desc:"Duração de Pokémon Ajudantes", connects_to: ["30"], prereqs: ["30"] },
                { id:"34", name:"Blindado", x:1224, y:1191, type: "armored", value: "2", unit: "%", desc:"Defesa do jogador", connects_to: ["30"], prereqs: ["30"] },
                { id:"35", name:"Essência Vital", x:1204, y:1246, type: "vital_essence", value: "2", unit: "%", desc:"Bônus de HP do Pokémon", connects_to: ["30"], prereqs: ["30"] },
                { id:"36", name:"Maestria em Defesa", x:1181, y:1289, type: "defense_mastery", value: "2", unit: "%", desc:"Chance de Bloquear Ataques de Pokémon", connects_to: ["30"], prereqs: ["30"] },
                { id:"37", name:"Recuperação Serena", x:1196, y:1329, type: "serene_recovery", value: "6", unit: "%", desc:"Regeneração de Energia Azul por intervalo em Mystery Dungeons", connects_to: ["30"], prereqs: ["30"] },
                { id:"38", name:"Blindado", x:1557, y:1342, type: "armored", value: "1", unit: "%", desc:"Defesa do jogador", connects_to: ["30", "44", "39"], prereqs: ["30"] },
                { id:"39", name:"Núcleo Carmesim", x:1473, y:1482, type: "crimson_core", value: "5", unit: "", desc:"Capacidade de Energia Vermelha em Mystery Dungeons", connects_to: ["38", "40"], prereqs: ["38", "40"] },
                { id:"40", name:"Núcleo Azul-Celeste", x:1329, y:1525, type: "blue_core", value: "8", unit: "", desc:"Capacidade de Energia Azul em Mystery Dungeons", connects_to: ["39", "41"], prereqs: ["39", "41"] },
                { id:"41", name:"Recuperação Serena", x:1211, y:1531, type: "serene_recovery", value: "6", unit: "%", desc:"Regeneração de Energia Azul por intervalo em Mystery Dungeons", connects_to: ["40", "42"], prereqs: ["40", "42"] },
                { id:"42", name:"Fluxo Ardente", x:1089, y:1507, type: "burning_flow", value: "5", unit: "%", desc:"Regeneração de Energia Vermelha por intervalo em Mystery Dungeons", connects_to: ["41", "43"], prereqs: ["41", "43"] },
                { id:"43", name:"Recuperação Serena", x:946, y:1454, type: "serene_recovery", value: "6", unit: "%", desc:"Regeneração de Energia Azul por intervalo em Mystery Dungeons", connects_to: ["42", "49"], prereqs: ["42", "49"] },
                { id:"44", name:"Corredor das Marés", x:1353, y:1353, type: "tide_runner", value: "35", unit: "MS", desc:"Velocidade de Surfe", connects_to: ["38", "45"], prereqs: ["38", "45"] },
                { id:"45", name:"Boost de Voo", x:1263, y:1390, type: "flyboost", value: "10", unit: "MS", desc:"Velocidade de Voo", connects_to: ["44", "46"], prereqs: ["44", "46"] },
                { id:"46", name:"Conhecimento da Irmandade", x:1153, y:1408, type: "brotherhood_knowledge", value: "10", unit: "%", desc:"Bônus de EXP para a Irmandade dos Duelistas", connects_to: ["45", "47"], prereqs: ["45", "47"] },
                { id:"47", name:"Conhecimento Diário", x:1057, y:1404, type: "daily_knowledge", value: "2", unit: "%", desc:"Bônus de EXP em Daily Kill e Daily Catch", connects_to: ["46", "48"], prereqs: ["46", "48"] },
                { id:"48", name:"Barreira de Eco", x:946, y:1376, type: "echo_barrier", value: "2", unit: "%", desc:"Dano Refletido do Pokémon", connects_to: ["47", "49"], prereqs: ["47", "49"] },
                { id:"49", name:"Maestria em Defesa", x:838, y:1347, type: "defense_mastery", value: "2", unit: "%", desc:"Chance de Bloquear Ataques de Pokémon", connects_to: ["48", "43", "50", "51", "52"], prereqs: ["48", "43", "50", "51", "52"] },
                { id:"50", name:"Capturador de Shinies", x:760, y:1418, type: "shiny_catcher", value: "3", unit: "%", desc:"Taxa de Captura aumentada para Pokémon Shinies", connects_to: ["49"], prereqs: ["49"] },
                { id:"51", name:"Saqueador Dimensional", x:750, y:1269, type: "dimensional_looter", value: "4", unit: "%", desc:"Bônus de Saque em Zonas Dimensionais", connects_to: ["49"], prereqs: ["49"] },
                { id:"52", name:"Capturador Dimensional", x:871, y:1211, type: "dimensional_catcher", value: "10", unit: "%", desc:"Taxa de Captura aumentada em Zonas Dimensionais", connects_to: ["49"], prereqs: ["49"] },
                { id:"53", name:"Colheita do Lugia", x:671, y:280, type: "lugia_harvest", value: "8", unit: "%", desc:"Guiado pela Harmonia Oceânica do Lugia, sua chance crítica de coleta em Profissões é aumentada", connects_to: [], prereqs: [], isSpecial: true },
                { id:"54", name:"Guardião da Vida", x:791, y:280, type: "guardian_of_life", value: "10", unit: "%", desc:"Guiado pela Harmonia Oceânica do Lugia, quando um Pokémon é revivido ou curado em um Centro Pokémon, ele recebe um Escudo que absorve dano equivalente a 10% do HP máximo", connects_to: [], prereqs: [], isSpecial: true}
            ]
        }
    ]
};